export type CountryOption = {
  readonly value: string;
  readonly label: string;
};

/** Pays en français — valeur envoyée à l’API (nom du pays). */
export const COUNTRY_OPTIONS: readonly CountryOption[] = [
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Afrique du Sud", label: "Afrique du Sud" },
  { value: "Allemagne", label: "Allemagne" },
  { value: "Algérie", label: "Algérie" },
  { value: "Belgique", label: "Belgique" },
  { value: "Bénin", label: "Bénin" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cameroun", label: "Cameroun" },
  { value: "Canada", label: "Canada" },
  { value: "Cap-Vert", label: "Cap-Vert" },
  { value: "République centrafricaine", label: "République centrafricaine" },
  { value: "Tchad", label: "Tchad" },
  { value: "Comores", label: "Comores" },
  { value: "Congo", label: "Congo" },
  { value: "République démocratique du Congo", label: "République démocratique du Congo" },
  { value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Égypte", label: "Égypte" },
  { value: "Émirats arabes unis", label: "Émirats arabes unis" },
  { value: "Espagne", label: "Espagne" },
  { value: "États-Unis", label: "États-Unis" },
  { value: "Éthiopie", label: "Éthiopie" },
  { value: "France", label: "France" },
  { value: "Gabon", label: "Gabon" },
  { value: "Gambie", label: "Gambie" },
  { value: "Ghana", label: "Ghana" },
  { value: "Guinée", label: "Guinée" },
  { value: "Guinée-Bissau", label: "Guinée-Bissau" },
  { value: "Guinée équatoriale", label: "Guinée équatoriale" },
  { value: "Haïti", label: "Haïti" },
  { value: "Inde", label: "Inde" },
  { value: "Italie", label: "Italie" },
  { value: "Japon", label: "Japon" },
  { value: "Kenya", label: "Kenya" },
  { value: "Liban", label: "Liban" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Mali", label: "Mali" },
  { value: "Maroc", label: "Maroc" },
  { value: "Maurice", label: "Maurice" },
  { value: "Mauritanie", label: "Mauritanie" },
  { value: "Mexique", label: "Mexique" },
  { value: "Monaco", label: "Monaco" },
  { value: "Niger", label: "Niger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Norvège", label: "Norvège" },
  { value: "Ouganda", label: "Ouganda" },
  { value: "Pays-Bas", label: "Pays-Bas" },
  { value: "Portugal", label: "Portugal" },
  { value: "Qatar", label: "Qatar" },
  { value: "Royaume-Uni", label: "Royaume-Uni" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Sénégal", label: "Sénégal" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "Singapour", label: "Singapour" },
  { value: "Soudan", label: "Soudan" },
  { value: "Suisse", label: "Suisse" },
  { value: "Tanzanie", label: "Tanzanie" },
  { value: "Togo", label: "Togo" },
  { value: "Tunisie", label: "Tunisie" },
  { value: "Turquie", label: "Turquie" },
  { value: "Autre", label: "Autre" },
] as const;

export const LANGUAGE_OPTIONS: readonly CountryOption[] = [
  { value: "FR", label: "Français" },
  { value: "EN", label: "English" },
] as const;
